#include <iostream>
#include <cmath>

/*
	Pentagon numbers
	Problem 44

    Pentagonal numbers are generated by the formula, 
    Pn=n(3n−1)/2. The first ten pentagonal numbers are:
        1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

    It can be seen that P4 + P7 = 22 + 70 = 92 = P8. 
    However, their difference, 70 − 22 = 48, is not pentagonal.

    Find the pair of pentagonal numbers, Pj and Pk, for which their sum and 
    difference are pentagonal and D = |Pk − Pj| is minimised; 
    what is the value of D?
*/

bool isPentagonNumber(int number)
{
    double t = (sqrt(24*number + 1.0) + 1.0) / 6.0;
    return t == (int)t;
} 

int main() 
{
    int answer = 0;
    bool found = false;
    int pk = 1;

    while (!found) 
    {
        pk++;
        int n = pk * (pk*3 - 1) / 2;

        for (int pj = pk-1; pj > 0; pj--) 
        {
            int m = pj * (3 * pj - 1) / 2;
            if (isPentagonNumber(n-m) && isPentagonNumber(n+m))
            {
                answer = n-m;
                found = true;
                break;
            }
        } 
    } 

    std::cout << "Answer: " << answer;    

    int c = 0;
    std::cin >> c;
    return 0;
}