#include <iostream>

using namespace std;

/*
	Project Euler Problem 2
	Even Fibonacci numbers

	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
int main() 
{
	int sum = 0;
	const int MAX = 4000000;

	int o = 1;
	int n = 1;
	int temp = 0;

	while (n < MAX)
	{
		temp = n;
		n = o + n;
		o = temp;
		if (n % 2 == 0)
		{
			sum += n;
		}
	}

	cout << "Sum: " << sum;
	int input;
	cin >> input;

	return 0;
}