-- Even Fibonacci numbers
-- Problem 2
--
-- Each new term in the Fibonacci sequence is generated by adding the previous
-- two terms. By starting with 1 and 2, the first 10 terms will be:
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
-- By considering the terms in the Fibonacci sequence whose values do not exceed four
-- million, find the sum of the even-valued terms.

fib :: Integer -> Integer
fib 0 = 1
fib 1 = 1
fib x = fib (x-1) + fib (x-2)

fibs :: [Integer]
fibs = 0 : scanl (+) 1 fibs

answer = sum $ filter even $ takeWhile (< 4000000) fibs
