/++
    Even Fibonacci numbers
    Problem 2
    
    Each new term in the Fibonacci sequence is generated by adding the previous
    two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four
    million, find the sum of the even-valued terms.
 +/

import std.stdio;

void main() {
    int f1 = 1;
    int f2 = 2;
    int sum = 0;

    while (f1 < 4000000) {
        if (f1 % 2 == 0) {
            sum += f1;
        }
        int tmp = f1 + f2;
        f1 = f2;
        f2 = tmp;
    }

    writeln(sum);
}